### ISSUE TITLE
Typescript declarations

### ISSUE THREAD

**Issue by Tauka** [diegohaz/redux-saga-thunk#18]
#### This package needs typescript declarations to pass ts compiler.

Since it has only one exported member, `index.d.ts` is going to contain just one line

```
export const middleware: any;
```

As per docs, no other API is exposed

*I'd like to open a PR, if you consider this necessary*

**Comment by diegohaz** [comment]
PR is welcome.

There're more exports though: https://github.com/diegohaz/redux-saga-thunk/blob/master/src/index.js

**Comment by Tauka** [comment]
Oh, yeah, missed those, I will add them as well
