### ISSUE TITLE
npm install redux-saga-thunk does not install index.d.ts file

### ISSUE THREAD

**Issue by Tauka** [diegohaz/redux-saga-thunk#23]
For some reason, `redux-saga-thunk` package does not include type definitions for Typescript

### Steps to reproduce
1. `npm install redux-saga-thunk`
2. Check `/node_modules/redux-saga-thunk` if it contains index.d.ts file
3. It does not

**Comment by diegohaz** [comment]
Hi, @Tauka. I think we need to add the file to the `files` section in package.json: https://github.com/diegohaz/redux-saga-thunk/blob/master/package.json#L16-L18

Or put it into `src`. I'm not sure how it works.

**Comment by Tauka** [comment]
Thank you for quick response @diegohaz 

Yeah, I think it will work, according to https://docs.npmjs.com/files/package.json#files. Will appreciate update of package.json

**Comment by diegohaz** [comment]
Released as `v0.6.1`
